# Projekt: Typografie a publikovani - 1
# Autor:   Aleksandr Shevchenko
# Datum:   03.03.2022 

all:
	latex proj1.tex
	latex proj1.tex
	dvips -t a4 proj1.dvi -o proj1.ps
	ps2pdf proj1.ps
clean:
	rm -rf proj1.ps proj1.pdf proj1.out proj1.log proj1.dvi proj1.aux
