# Projekt: Typografie a publikovani - 2
# Autor:   Aleksandr Shevchenko
# Datum:   11.03.2022 

all:
	latex proj2.tex
	latex proj2.tex
	dvips -t a4 proj2.dvi -o proj2.ps
	ps2pdf proj2.ps
clean:
	rm -rf proj2.ps proj2.pdf proj2.out proj2.log proj2.dvi proj2.aux
