version: '3.1'

services:
  db:
    container_name: iis-postgresql
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    
