# Projekt: Typografie a publikovani - 5
# Autor:   Aleksandr Shevchenko
# Datum:   28.04.2022 

all:
	pdflatex proj5.tex
	pdflatex proj5.tex
clean:
	rm -rf proj5.ps proj5.pdf proj5.out proj5.log proj5.dvi proj5.aux proj5.bbl proj5.blg proj5.vrb proj5.toc proj5.snm proj5.nav
