# Projekt: Typografie a publikovani - 4
# Autor:   Aleksandr Shevchenko
# Datum:   14.04.2022 

all:
	pdflatex proj4.tex
	bibtex proj4
	pdflatex proj4.tex
	pdflatex proj4.tex
clean:
	rm -rf proj4.ps proj4.pdf proj4.out proj4.log proj4.dvi proj4.aux proj4.bbl proj4.blg
